/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teistris.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import teistris.model.Game;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import teistris.model.Game;

/**
 *
 * @author iago.franciscoperez
 */
public class TeistrisPanel extends javax.swing.JFrame {

    public Timer timer;
    int delay=1000;
    private int linesCount =0;

    /**
     * Creates new form NewJFrame
     */
    public TeistrisPanel() {
        initComponents();
    }

    private Game game = null; // Referenza ao obxecto do xogo actual

    /**
     * Pinta un cadrado no panel de cadrados
     *
     * @param lblSquare Etiqueta co cadrado que se quere pintar no panel
     */
    public void drawSquare(JLabel lblSquare) {
        panel_Juego.add(lblSquare);
        panel_Juego.repaint();
    }

    /**
     * Borra un cadrado do panel de cadrados
     *
     * @param lblSquare Etiqueta co cadrado que se quere borrar do panel
     */
    public void deleteSquare(JLabel lblSquare) {
        panel_Juego.remove(lblSquare);
        panel_Juego.repaint();
    }

    /**
     * Actualiza na ventá o número de liñas que van feitas no xogo
     *
     * @param numberOfLines Número de liñas feitas no xogo
     */
    public void showNumberOfLines(int numberOfLines) {
        lineasN.setText(String.valueOf(numberOfLines));
        linesCount += numberOfLines;
        if (linesCount !=0){
            timer.setDelay(timer.getDelay() / 2);
        } else {
        }
       
    }

    /**
     * Mostra unha mensaxe informando ao usuario do final do xogo
     */
    public void showGameOver() {
        game = null;
        JOptionPane.showMessageDialog(this, "Fin do xogo");
    }

    /**
     * Inicia un novo xogo
     */
    private void startGame() {
        // Limpamos todo o que puidese haber pintado no panel do xogo
        panel_Juego.removeAll();
        // Creamos un novo obxecto xogo
        game = new Game(this);
        // Desactivamos o botón de pausa
        pausa_button.setSelected(false);
        // Establecemos o número de liñas que se mostran na ventá a cero
        lineasN.setText("0");
        if (timer == null) {
            timer = new Timer(delay, null);
            timer.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                   game.movePieceDown();
                }
            });
        } else {
            delay = 1000;
            timer.setDelay(delay);
            timer.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        newgame_button = new javax.swing.JButton();
        pausa_button = new javax.swing.JButton();
        liñasLabel = new javax.swing.JLabel();
        lineasN = new javax.swing.JLabel();
        panel_Juego = new javax.swing.JPanel();
        rotate_Button = new javax.swing.JButton();
        down_button = new javax.swing.JButton();
        right_Button = new javax.swing.JButton();
        left_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teistris");

        panel_fondo.setBackground(new java.awt.Color(0, 0, 0));

        newgame_button.setText("Nova partida");
        newgame_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgame_buttonActionPerformed(evt);
            }
        });

        pausa_button.setText("Pausa");
        pausa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausa_buttonActionPerformed(evt);
            }
        });

        liñasLabel.setForeground(new java.awt.Color(255, 255, 255));
        liñasLabel.setText("Liñas:");

        lineasN.setForeground(new java.awt.Color(255, 255, 255));

        panel_Juego.setPreferredSize(new java.awt.Dimension(240, 280));

        javax.swing.GroupLayout panel_JuegoLayout = new javax.swing.GroupLayout(panel_Juego);
        panel_Juego.setLayout(panel_JuegoLayout);
        panel_JuegoLayout.setHorizontalGroup(
            panel_JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_JuegoLayout.setVerticalGroup(
            panel_JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        rotate_Button.setText("Rotar");
        rotate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotate_ButtonActionPerformed(evt);
            }
        });

        down_button.setText("Abaixo");
        down_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_buttonActionPerformed(evt);
            }
        });

        right_Button.setText("->");
        right_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_ButtonActionPerformed(evt);
            }
        });

        left_Button.setText("<-");
        left_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Iago");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alex");

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(newgame_button, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addComponent(pausa_button)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addComponent(lineasN)
                        .addGap(23, 23, 23))))
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_Juego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(liñasLabel)
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(4, 4, 4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(left_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(down_button)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addComponent(rotate_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(right_Button)))
                .addGap(44, 44, 44))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newgame_button)
                    .addComponent(pausa_button))
                .addGap(18, 18, 18)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(liñasLabel)
                    .addComponent(lineasN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Juego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(left_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(right_Button)
                    .addComponent(rotate_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(down_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pausa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausa_buttonActionPerformed
        if (game != null) {
            game.setPaused(pausa_button.isSelected());
        }
    }//GEN-LAST:event_pausa_buttonActionPerformed

    private void newgame_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgame_buttonActionPerformed
        startGame();
        timer.start();
    }//GEN-LAST:event_newgame_buttonActionPerformed

    private void rotate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotate_ButtonActionPerformed
        if (game != null) {
            game.rotatePiece();
        }
    }//GEN-LAST:event_rotate_ButtonActionPerformed

    private void left_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_ButtonActionPerformed
        if (game != null) {
            game.movePieceLeft();
        }
    }//GEN-LAST:event_left_ButtonActionPerformed

    private void right_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_ButtonActionPerformed
        if (game != null) {
            game.movePieceRight();
        }
    }//GEN-LAST:event_right_ButtonActionPerformed

    private void down_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_buttonActionPerformed
        if (game != null) {
            game.movePieceDown();
        }
    }//GEN-LAST:event_down_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeistrisPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeistrisPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeistrisPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeistrisPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeistrisPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton down_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton left_Button;
    private javax.swing.JLabel lineasN;
    private javax.swing.JLabel liñasLabel;
    private javax.swing.JButton newgame_button;
    private javax.swing.JPanel panel_Juego;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JButton pausa_button;
    private javax.swing.JButton right_Button;
    private javax.swing.JButton rotate_Button;
    // End of variables declaration//GEN-END:variables
}
